# Generated by Django 4.2.1 on 2023-05-16 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('notebook_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('notebook_name', models.CharField(default='New Notebook', max_length=512)),
                ('notebook_color', models.CharField(default='Blue', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('page_name', models.CharField(default='New Page', max_length=256)),
                ('page_color', models.CharField(default='Blue', max_length=128)),
                ('list_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.notebook')),
            ],
        ),
        migrations.CreateModel(
            name='List_object',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(default=None, max_length=2048, null=True)),
                ('indent_level', models.IntegerField(default=0)),
                ('font', models.JSONField(default={'color': 'black', 'font': 'Arial, Helvetica, sans-serif', 'size': 'medium', 'style': None})),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now_add=True)),
                ('parent_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.list')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='parent_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.page'),
        ),
    ]
